name: Deploy Github pages in Production
run-name: ${{ github.actor }} runner is job
on:
 push:
  branches:
    - release 
 
jobs:
    deploy:
      runs-on: ubuntu-latest
  
      steps:
        - name: Change directory
          run: cd website

        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
  
        - name: Install dependencies
          run: npm install
  
        - name: Build site
          run: npm run build
  
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            
