# Builds and published Dashy's documentation website
name: 📝 Build Docs Site
on:
  workflow_dispatch:
    inputs:
      deploy_options:
        description: 'Deploy Production'
        required: true
        type: choice
        options:
        - START
        - NONE
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: ./website
    if: inputs.deploy_options == 'START'
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: ${{ github.actor }}
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages