name: Deploy Github pages in Production
run-name: ${{ github.actor }} started deploy new version
on:
 workflow_dispatch:
   inputs:
    deploy_options:
       description: 'Deploy Production'
       required: true
       type: choice
       options:
         - START
         - NONE
 
jobs:
    deploy_site:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./website
      if:  ${{ inputs.deploy_options == 'START' }}            
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 18
  
        - name: Install dependencies
          run: npm install
  
        - name: Build site
          run: npm run build
  
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build
            
