name: PR Validation
run-name: PR of ${{ github.actor }} 

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions: write-all
 
jobs:
    PR:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pullRequest = context.payload.pull_request;
            console.log(`O ID da PR é: ${pullRequest.id}`);

    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./website
      steps:

        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Comment PR
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              **Comentário da Pull Request:**

              * Autor: ${{ github.event.pull_request.user.login }}
              * Branch: ${{ github.event.pull_request.head.ref }}
              * Link para PR: ${{ github.event.pull_request.url }}

              **Observações:**
              > Iniciando validacao do build.
            pr_number: ${{ github.event.pull_request.number }}

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 18
            # cache: npm
        - name: Install dependencies
          run: npm install

        - name: Build site
          id: buildTests
          run: npm run build

        - name: Comment PR (Failed)
          if: failure() && steps.buildTests.outcome == 'failure'
          uses: thollander/actions-comment-pull-request@v2
          with:
            message: |
              Verify build is failed ! :failed:
            pr_number: ${{ github.event.pull_request.number }}    
              
      
            